menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/yaggjs/yagg-cli
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: yaggjs-github-io

# Analytics
# google-analytics:
ga: UA-110192490-1

# Copyright Infomation
startyear: 2017
